<a href="https://colab.research.google.com/github/balladembelemoussa/codesandbox-template-nuxt/blob/main/1NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [ ]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
mon_array_bidimensionnel=np.array([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
mon_array_bidimensionnel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
sous_tableau=notre_tableau[0:5]

In [ ]:
sous_tableau

array([1, 2, 3, 4, 5])

In [ ]:
sous_tableau[0]=10

In [ ]:
sous_tableau

array([10,  2,  3,  4,  5])

In [ ]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
notre_tableau=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [ ]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
sous_tableau=notre_tableau[0:5].copy()

In [ ]:
sous_tableau

array([1, 2, 3, 4, 5])

In [ ]:
sous_tableau[0]=10

In [ ]:
sous_tableau

array([10,  2,  3,  4,  5])

In [ ]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
mon_array_bidimensionnel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mon_array_bidimensionnel[1,2]

6

In [ ]:
mon_array_bidimensionnel[1,-1]

6

In [ ]:
mon_array_bidimensionnel[:,0]

array([1, 4, 7])

In [ ]:
mon_array_bidimensionnel[0,:]

array([1, 2, 3])

In [ ]:
mon_array_bidimensionnel[:,0:3:2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [ ]:
mon_array_bidimensionnel[:,-1]

array([3, 6, 9])

In [ ]:
mon_array_bidimensionnel[:,1:-1]

array([[2],
       [5],
       [8]])

In [ ]:
mon_array_bidimensionnel[2,1:-1]

array([8])

In [ ]:
array=np.random.randint(100,size=(6,4))

In [ ]:
array

array([[16, 29, 68, 99],
       [57, 20, 38, 42],
       [66, 69, 24, 51],
       [61, 31, 47, 36],
       [47,  7, 81, 23],
       [21,  8, 52, 75]])

In [ ]:
array.ndim

2

In [ ]:
array.shape

(6, 4)

In [ ]:
array.dtype

dtype('int32')

In [ ]:
array.size

24

In [ ]:
array[array>50]

array([68, 99, 57, 66, 69, 51, 61, 81, 52, 75])

In [ ]:
array>50

array([[False, False,  True,  True],
       [ True, False, False, False],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

In [ ]:
array[array>=50]

array([68, 99, 57, 66, 69, 51, 61, 81, 52, 75])

In [ ]:
array[array<50]

array([16, 29, 20, 38, 42, 24, 31, 47, 36, 47,  7, 23, 21,  8])

In [ ]:
array[array==50]

array([], dtype=int32)

In [ ]:
array[array!=50]

array([16, 29, 68, 99, 57, 20, 38, 42, 66, 69, 24, 51, 61, 31, 47, 36, 47,
        7, 81, 23, 21,  8, 52, 75])

In [ ]:
# & : and
# | : or
array[(array >=50) & (array <=70)]

array([68, 57, 66, 69, 51, 61, 52])

In [ ]:
array[(array>=50) | (array<=40)]

array([16, 29, 68, 99, 57, 20, 38, 66, 69, 24, 51, 61, 31, 36,  7, 81, 23,
       21,  8, 52, 75])

In [ ]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
array2=np.array([[2,5,6],[9,10,11],[5,6,9]])

In [ ]:
np.concatenate([array1,array2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9]])

In [ ]:
array3=np.array([[4,10,13], [7,14,15], [10,16,84]])

In [ ]:
np.concatenate([array1, array2, array3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9],
       [ 4, 10, 13],
       [ 7, 14, 15],
       [10, 16, 84]])

In [ ]:
array1=np.array([15,16,47])

In [ ]:
array1

array([15, 16, 47])

In [ ]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.vstack([array1,array2])

array([[15, 16, 47],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
array1=np.array([[15], [16], [47]])

In [ ]:
array1

array([[15],
       [16],
       [47]])

In [ ]:
np.hstack([array1,array2])

array([[15,  1,  2,  3],
       [16,  4,  5,  6],
       [47,  7,  8,  9]])

In [ ]:
array=np.array([15,16,17,12,49,52,12,14,36])

In [ ]:
len(array)

9

In [ ]:
np.split(array,[2,6])

[array([15, 16]), array([17, 12, 49, 52]), array([12, 14, 36])]

In [ ]:
array1,array2,array3=np.split(array,[2,6])

In [ ]:
print(array1,array2,array3)

[15 16] [17 12 49 52] [12 14 36]


In [ ]:
array1,array2,array3,array4=np.split(array,[2,4,6])

In [ ]:
print(array1,array2,array3,array4)

[15 16] [17 12] [49 52] [12 14 36]


In [ ]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
array1,array1bis=np.vsplit(array2, [2])
print(array1,array1bis)

[[1 2 3]
 [4 5 6]] [[7 8 9]]


In [ ]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array1,array1bis=np.hsplit(array2,[2])
print(array1,array1bis)

[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


In [ ]:
array=np.random.randint(350, size=(10,9))

In [ ]:
array

array([[ 26, 260, 149, 200, 106,  11,  16,  10, 285],
       [136,  75, 287,   1, 261,  67,  47,  94, 218],
       [225, 260, 212,  83, 318, 256, 220, 150, 148],
       [115, 248, 229, 338, 149,  39, 161, 292,  54],
       [  1, 318, 192,   2, 221,  46, 192, 208, 122],
       [ 59,  82,  45, 271, 246, 123, 158, 154, 190],
       [289, 230, 197, 205,  41,  50, 196, 272, 276],
       [310, 103, 178, 251, 191, 168, 233, 324, 142],
       [ 95, 279, 317, 277, 244,  78, 274, 241,  13],
       [ 15, 259,   0, 149, 199, 296, 193, 271,  36]])

In [ ]:
array + 2

array([[ 28, 262, 151, 202, 108,  13,  18,  12, 287],
       [138,  77, 289,   3, 263,  69,  49,  96, 220],
       [227, 262, 214,  85, 320, 258, 222, 152, 150],
       [117, 250, 231, 340, 151,  41, 163, 294,  56],
       [  3, 320, 194,   4, 223,  48, 194, 210, 124],
       [ 61,  84,  47, 273, 248, 125, 160, 156, 192],
       [291, 232, 199, 207,  43,  52, 198, 274, 278],
       [312, 105, 180, 253, 193, 170, 235, 326, 144],
       [ 97, 281, 319, 279, 246,  80, 276, 243,  15],
       [ 17, 261,   2, 151, 201, 298, 195, 273,  38]])

In [ ]:
array - 2

array([[ 24, 258, 147, 198, 104,   9,  14,   8, 283],
       [134,  73, 285,  -1, 259,  65,  45,  92, 216],
       [223, 258, 210,  81, 316, 254, 218, 148, 146],
       [113, 246, 227, 336, 147,  37, 159, 290,  52],
       [ -1, 316, 190,   0, 219,  44, 190, 206, 120],
       [ 57,  80,  43, 269, 244, 121, 156, 152, 188],
       [287, 228, 195, 203,  39,  48, 194, 270, 274],
       [308, 101, 176, 249, 189, 166, 231, 322, 140],
       [ 93, 277, 315, 275, 242,  76, 272, 239,  11],
       [ 13, 257,  -2, 147, 197, 294, 191, 269,  34]])

In [ ]:
array * 10

array([[ 260, 2600, 1490, 2000, 1060,  110,  160,  100, 2850],
       [1360,  750, 2870,   10, 2610,  670,  470,  940, 2180],
       [2250, 2600, 2120,  830, 3180, 2560, 2200, 1500, 1480],
       [1150, 2480, 2290, 3380, 1490,  390, 1610, 2920,  540],
       [  10, 3180, 1920,   20, 2210,  460, 1920, 2080, 1220],
       [ 590,  820,  450, 2710, 2460, 1230, 1580, 1540, 1900],
       [2890, 2300, 1970, 2050,  410,  500, 1960, 2720, 2760],
       [3100, 1030, 1780, 2510, 1910, 1680, 2330, 3240, 1420],
       [ 950, 2790, 3170, 2770, 2440,  780, 2740, 2410,  130],
       [ 150, 2590,    0, 1490, 1990, 2960, 1930, 2710,  360]])

In [ ]:
array[:,0] * 10

array([ 260, 1360, 2250, 1150,   10,  590, 2890, 3100,  950,  150])

In [ ]:
array / 2 

array([[ 13. , 130. ,  74.5, 100. ,  53. ,   5.5,   8. ,   5. , 142.5],
       [ 68. ,  37.5, 143.5,   0.5, 130.5,  33.5,  23.5,  47. , 109. ],
       [112.5, 130. , 106. ,  41.5, 159. , 128. , 110. ,  75. ,  74. ],
       [ 57.5, 124. , 114.5, 169. ,  74.5,  19.5,  80.5, 146. ,  27. ],
       [  0.5, 159. ,  96. ,   1. , 110.5,  23. ,  96. , 104. ,  61. ],
       [ 29.5,  41. ,  22.5, 135.5, 123. ,  61.5,  79. ,  77. ,  95. ],
       [144.5, 115. ,  98.5, 102.5,  20.5,  25. ,  98. , 136. , 138. ],
       [155. ,  51.5,  89. , 125.5,  95.5,  84. , 116.5, 162. ,  71. ],
       [ 47.5, 139.5, 158.5, 138.5, 122. ,  39. , 137. , 120.5,   6.5],
       [  7.5, 129.5,   0. ,  74.5,  99.5, 148. ,  96.5, 135.5,  18. ]])

In [ ]:
np.add(array,2)

array([[ 28, 262, 151, 202, 108,  13,  18,  12, 287],
       [138,  77, 289,   3, 263,  69,  49,  96, 220],
       [227, 262, 214,  85, 320, 258, 222, 152, 150],
       [117, 250, 231, 340, 151,  41, 163, 294,  56],
       [  3, 320, 194,   4, 223,  48, 194, 210, 124],
       [ 61,  84,  47, 273, 248, 125, 160, 156, 192],
       [291, 232, 199, 207,  43,  52, 198, 274, 278],
       [312, 105, 180, 253, 193, 170, 235, 326, 144],
       [ 97, 281, 319, 279, 246,  80, 276, 243,  15],
       [ 17, 261,   2, 151, 201, 298, 195, 273,  38]])

In [ ]:
np.subtract(array,7)

array([[ 19, 253, 142, 193,  99,   4,   9,   3, 278],
       [129,  68, 280,  -6, 254,  60,  40,  87, 211],
       [218, 253, 205,  76, 311, 249, 213, 143, 141],
       [108, 241, 222, 331, 142,  32, 154, 285,  47],
       [ -6, 311, 185,  -5, 214,  39, 185, 201, 115],
       [ 52,  75,  38, 264, 239, 116, 151, 147, 183],
       [282, 223, 190, 198,  34,  43, 189, 265, 269],
       [303,  96, 171, 244, 184, 161, 226, 317, 135],
       [ 88, 272, 310, 270, 237,  71, 267, 234,   6],
       [  8, 252,  -7, 142, 192, 289, 186, 264,  29]])

In [ ]:
np.multiply(array,10)

array([[ 260, 2600, 1490, 2000, 1060,  110,  160,  100, 2850],
       [1360,  750, 2870,   10, 2610,  670,  470,  940, 2180],
       [2250, 2600, 2120,  830, 3180, 2560, 2200, 1500, 1480],
       [1150, 2480, 2290, 3380, 1490,  390, 1610, 2920,  540],
       [  10, 3180, 1920,   20, 2210,  460, 1920, 2080, 1220],
       [ 590,  820,  450, 2710, 2460, 1230, 1580, 1540, 1900],
       [2890, 2300, 1970, 2050,  410,  500, 1960, 2720, 2760],
       [3100, 1030, 1780, 2510, 1910, 1680, 2330, 3240, 1420],
       [ 950, 2790, 3170, 2770, 2440,  780, 2740, 2410,  130],
       [ 150, 2590,    0, 1490, 1990, 2960, 1930, 2710,  360]])

In [ ]:
np.divide(array, 50)

array([[0.52, 5.2 , 2.98, 4.  , 2.12, 0.22, 0.32, 0.2 , 5.7 ],
       [2.72, 1.5 , 5.74, 0.02, 5.22, 1.34, 0.94, 1.88, 4.36],
       [4.5 , 5.2 , 4.24, 1.66, 6.36, 5.12, 4.4 , 3.  , 2.96],
       [2.3 , 4.96, 4.58, 6.76, 2.98, 0.78, 3.22, 5.84, 1.08],
       [0.02, 6.36, 3.84, 0.04, 4.42, 0.92, 3.84, 4.16, 2.44],
       [1.18, 1.64, 0.9 , 5.42, 4.92, 2.46, 3.16, 3.08, 3.8 ],
       [5.78, 4.6 , 3.94, 4.1 , 0.82, 1.  , 3.92, 5.44, 5.52],
       [6.2 , 2.06, 3.56, 5.02, 3.82, 3.36, 4.66, 6.48, 2.84],
       [1.9 , 5.58, 6.34, 5.54, 4.88, 1.56, 5.48, 4.82, 0.26],
       [0.3 , 5.18, 0.  , 2.98, 3.98, 5.92, 3.86, 5.42, 0.72]])

In [ ]:
np.mean(array)

169.64444444444445

In [ ]:
array.mean()

169.64444444444445

In [ ]:
array.min()

0

In [ ]:
array.max()

338

In [ ]:
np.mean(array, axis=0)

array([127.1, 211.4, 180.6, 177.7, 197.6, 113.4, 169. , 201.6, 148.4])

In [ ]:
np.mean(array, axis=1)

array([118.11111111, 131.77777778, 208.        , 180.55555556,
       144.66666667, 147.55555556, 195.11111111, 211.11111111,
       202.        , 157.55555556])

In [ ]:
houses = np.genfromtxt("Houses.csv", delimiter=",", dtype=int)

In [ ]:
houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [ ]:
#1. Convertir le prix des maisons en euros, sachant que 1 dollar = 0.86 euros
houses[:,0]=houses[:,0]*0.86

In [ ]:
print(houses)

[[182320   4148  25264]
 [197800   2501  11891]
 [291540   4374  25351]
 [248540   2398  22215]
 [137600   2536   9234]
 [ 73100   2368  13329]
 [ 73100   1264   8407]
 [124700   1572  12588]
 [141040   2375  16204]
 [106210   1161   9626]
 [154800   1542   8755]
 [137170   1464  14636]
 [134160   2240  21780]
 [125990   1269  11250]
 [ 87290    924   7361]
 [ 94428    768  10497]
 [156520   1320  15768]
 [ 94600   1845  12153]
 [107500   1274  13634]
 [ 68800   1905  10890]]


In [ ]:
#2. Convertir les pieds carrés en m² sachant que 1 pied carré = 0.09 m²
houses[:,1:]=houses[:,1:]*0.09

In [ ]:
print(houses)

[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]


In [ ]:
# 3. Combien de maisons ont un terrain de plus de 1000 m²
len(houses[houses[:,2]>1000])

13

In [ ]:
# 4. Calculer la somme totale obtenue après la vente de toutes les maisons.
np.sum(houses[:,0])

2737208

In [ ]:
# 5. Quelle est la taille de la maison vendue la plus chère ?
prix_max=np.max(houses[:,0])
print(prix_max)

291540


In [ ]:
houses[houses[:,0] == prix_max]

array([[291540,    393,   2281]])

In [ ]:
# 6. casser l'array en trois tableau et le concaténer à nouveau pour obtenir le tableau initial
prix,taille_maison,taille_terrain=np.hsplit(houses, 3)

In [ ]:
houses_original=np.concatenate([prix, taille_maison, taille_terrain], axis = 1)

In [ ]:
print(houses_original)

[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]
